Topic1:
  Brokers:
    - 192.168.1.101:34150
  Topic: topic1
  Conns: 1
  Processors: 1
  Channel: channel1

Topic2:
  Brokers:
    - 192.168.1.101:34150
  Topic: topic2
  Conns: 1
  Processors: 1
  Channel: channel2