PulsarTopic1:
  Brokers:
    - 127.0.0.1:6650
  Topic: topic1
  Conns: 1
  Processors: 1
  SubscriptionName: sub_topic1

PulsarTopic2:
  Brokers:
    - 127.0.0.1:6650
  Topic: topic2
  Conns: 1
  Processors: 1
  SubscriptionName: sub_topic2