PulsarTopic1:
  Name: pulsar
  Brokers:
    - 192.168.1.101:6650
  Topic: topic_message
  Conns: 1
  Processors: 1
  SubscriptionName: topic_message

PulsarTopic2:
  Name: pulsar
  Brokers:
    - 114.115.255.244:6650
  Topic: topic2
  Conns: 1
  Processors: 1
  SubscriptionName: topic2