PulsarTopic1:
  Name: pulsar
  Brokers:
    - 114.115.255.244:6650
  Topic: topic1
  Conns: 1
  Processors: 1
  SubscriptionName: topic1

PulsarTopic2:
  Name: pulsar
  Brokers:
    - 114.115.255.244:6650
  Topic: topic2
  Conns: 1
  Processors: 1
  SubscriptionName: topic2