Name: pulsar
Brokers:
  - 127.0.0.1:6650
AuthName: token
AuthParams: '{"token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.CNYN8h04Z_wJcvNssVhcyZKDlqvwOSxmkXeOy6WH8pM"}'
Topic: topic1
SubscriptionName: sub_topic1